### ISSUE TITLE
How to understand this module?

### ISSUE THREAD

**Issue by geoidesic** [kandashi/midi-srd#10]
Looking at the Effects for Misty Step...
![Screenshot 2022-01-17 at 10 06 59](https://user-images.githubusercontent.com/4637995/149731281-707b34e2-93fc-41e7-9582-7ed986c885d9.png)
What should I understand from this?
* What is `macro-itemMacro` and where would I find this macro?
* What does the `Effect Value` represent?
* If I wanted to add my own effects to a spell, how would I go about this?
* Am I asking these questions in the right place?

**Comment by kandashi** [comment]
These are all questions for DAE or core active effects, not this module
