### ISSUE TITLE
Sneak Attack not working properly

### ISSUE THREAD

**Issue by ravingdragoon** [kandashi/midi-srd#3]
It seems that Sneak Attack is not functioning when the rogue attacks with advantage and there are no allies within 5 feet of the target. Is this intentional and/or not implementable?

**Comment by thatlonelybugbear** [comment]
I cannot seem to find a Sneak Attack on the MIDI-SRD compendium? Do you maybe mean Midi-QOL and that question should be directed here: https://gitlab.com/tposney/midi-qol  ??

**Comment by ravingdragoon** [comment]
> I cannot seem to find a Sneak Attack on the MIDI-SRD compendium? Do you maybe mean Midi-QOL and that question should be directed here: https://gitlab.com/tposney/midi-qol ??

Apologies, apparently this needs to go in the dae-srd issues, not here..
