### ISSUE TITLE
Manifest can't be found

### ISSUE THREAD

**Issue by geoidesic** [kandashi/midi-srd#35]
<img width="586" alt="Screenshot 2023-01-30 at 21 53 37" src="https://user-images.githubusercontent.com/4637995/215604025-7808508a-dc73-44af-8d61-61dcb09bacf3.png">

latest versions of everything

**Comment by thatlonelybugbear** [comment]
This has nothing to do with Kandashi's official repository of Midi SRD.

It's a fork I created to update MidiSRD for v10 compatibility.
I would close this issue and if the error persists hit me up in either discord or the forked git.

Use this instead: <https://raw.githubusercontent.com/thatlonelybugbear/midi-srd/master/module.json>
