### ISSUE TITLE
Installing midi-srd from foundry gives this error

### ISSUE THREAD

**Issue by MokoPolo** [kandashi/midi-srd#36]
[midi-srd] Metadata validation failed for module "midi-srd": The file "scripts/midiSRD-styles.css" included by module midi-srd does not exist

**Comment by MaineKnight** [comment]
Here are the errors logged today when attempting to install/run (listed version is 0.2.03)

![midi-srd](https://user-images.githubusercontent.com/125476146/219745217-656ecff6-922e-450c-96a0-1f050d8ba9a3.jpg)

**Comment by MokoPolo** [comment]
It seems this error has been around for awhile. I wonder if this repo is dead. Temp fix is go to \AppData\Local\FoundryVTT\Data\modules\midi-srd (this is for windows OS) and modify line in module.json:

    "styles": [
        "scripts/midiSRD-style.css"
    ],

Restart foundry server

**Comment by greentwelve** [comment]
From Mr. Primate's Discord server:
"MrPrimate: midi-srd provided a bunch of effects for [Midi-QoL], but isn't supported in v10"

**Comment by thatlonelybugbear** [comment]
I will be updating the MidiSRD for Foundry v10 soon

**Comment by MokoPolo** [comment]
Thanks! I just got foundry. I hadn't realized that v10 was still new. Thanks!
