### ISSUE TITLE
Support with foundry v9.X

### ISSUE THREAD

**Issue by CaosFR** [kandashi/midi-srd#8]
Hi,

Simple question that many would like to know. Is your module compatible with v9.X? Have any tests been carried out?

I'm refer to : https://docs.google.com/spreadsheets/d/1ppPR348igxL75M_G7dWl3otzXYpPwrnj7NVSDP8GmVw/edit#gid=0

Thanks
Bests regards

**Comment by justinross** [comment]
Using this pack, I've noticed at least a couple of issues in v9. Spells (arcane sword, IIRC) throwing "tactor.createowneditem" errors, for example.

**Comment by kandashi** [comment]
Any spells/items with macros will likely have broken

**Comment by CaosFR** [comment]
that's a shame, thanks for reply

**Comment by justinross** [comment]
The fixes will likely be pretty easy in most cases. Replacing cases of “createEmbeddedItem” with “createEmbeddedEntities” and wrapping the new item with an array [].

**Comment by CaosFR** [comment]
is theire any plan for update ?

**Comment by kandashi** [comment]
yes, but I need some time that I dont have right now.

**Comment by CaosFR** [comment]
Of course, take all your time you need. My question is just for information
